// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PluginCommonBase","status":true,"description":"Plugin Analysis Common Base","parameters":{}},
{"name":"PluginBaseFunction","status":true,"description":"Plugin Common Functions","parameters":{}},
{"name":"AltSaveScreen","status":true,"description":"Alternative save/load screen layout.","parameters":{}},
{"name":"GALV_MessageBustsMZ","status":true,"description":"(v.1.2) Displays a bust image instead of selected face image","parameters":{"bPriority":"1","bPosition":"1","bX":"0","bY":"-5","xOffset":"390","fileAppend":"","mStyleBusts":"false"}},
{"name":"PlayMsgWndCharSeMZ","status":true,"description":"[Ver1.1.0]Play SE for Each Letter on Message Window","parameters":{"default SE":"1","battle default SE":"0","interval":"2","name1":"Message","volume1":"15","pitch1":"150","name2":"Message","volume2":"55","pitch2":"50","name3":"","volume3":"90","pitch3":"100","name4":"","volume4":"90","pitch4":"100","name5":"","volume5":"90","pitch5":"100","advanced":"","prefix":"SE"}},
{"name":"Followers","status":true,"description":"","parameters":{}},
{"name":"AltMenuScreen2MZ","status":true,"description":"[Ver1.5.0]Yet another menu screen layout","parameters":{"allowWindowDisp":"false","maxColsMenu":"4","commandRows":"2","commandCols":"4","isDisplayStatus":"true","doesDisplayNextLevel":"false","textNextLevel":"Next%1","statusStyle":"standard","display map name":"false","location string":"Location:","bgBitmapMenu":"Menu","doesNotSetItemScene":"true","bgBitmapItem":"","doesNotSetSkillScene":"true","bgBitmapSkill":"","doesNotSetEquipScene":"true","bgBitmapEquip":"","doesNotSetStatusScene":"true","bgBitmapStatus":"","doesNotSetOptionScene":"true","bgBitmapOptions":"","doesNotSetSaveScene":"true","bgBitmapFile":"","doesNotSetEndScene":"true","bgBitmapGameEnd":"","doesNotSetShopScene":"false","bgBitmapShop":"","doesNotSetNameScene":"true","bgBitmapNameInput":"","bgUserDefined":""}},
{"name":"FilterControllerMZ","status":true,"description":"FilterControllerMZ","parameters":{"decimalVariable":"true","displacementImage":"DisplacementMap","global-enable Settings":"","enabledAll-ShowInOptionMenu":"false","enabledAll-Text":"Filter Effects Enabled","enabledAll-DefaultValue":"true"}},
{"name":"GALV_CharacterFramesMZ","status":true,"description":"(v.1.0) Enables map character sheets to have more frames per character.","parameters":{"fSpeedMod":"f * 0.8","fileSymbol":"x"}},
{"name":"MZPlusQuickStart","status":true,"description":"<MZPlusQuickStart> Skips the title for fast testing. (Will only skip the title in dev mode).  Credit to Quasi.","parameters":{"Dev Mode Only":"false"}}
];
